"""Mapping between CSV column names (short codes) and full display names"""

# Mapping from short code to full name
COLUMN_TO_FULLNAME = {
    # Broad Market Indices
    'N50': 'Nifty 50',
    'NN50': 'Nifty Next 50',
    'N100': 'Nifty 100',
    'N200': 'Nifty 200',
    'NTOTLM': 'NIFTY TOTAL MKT',
    'N500': 'Nifty 500',
    'NMC5025': 'Nifty500 Multicap 50:25:25',
    'NMC50': 'Nifty Midcap 50',
    'N500EQ': 'Nifty500 EW',
    'NMC150': 'NIFTY MIDCAP 150',
    'NMCSEL': 'NIFTY MID SELECT',
    'NMC100': 'NIFTY MIDCAP 100',
    'NSC250': 'NIFTY SMLCAP 250',
    'NSC50': 'NIFTY SMLCAP 50',
    'NSC100': 'NIFTY SMLCAP 100',
    'NMICRO': 'NIFTY MICROCAP250',
    'NLMC250': 'NIFTY LARGEMID250',
    'NMSC400': 'NIFTY MIDSML 400',
    'NT10EWT': 'Nifty Top 10 EW',
    'NT15EWT': 'Nifty Top 15 EW',
    'NT20EWT': 'Nifty Top 20 EW',
    'N50EQWGT': 'NIFTY50 EQL WGT',
    'NIFTY500 EQUAL WEIGHT.1': 'Nifty500 LMS Eql',
    'N100LIQ15': 'Nifty100 Liq 15',
    'NMCL15': 'Nifty Mid Liq 15',
    
    # Sectoral Indices
    'NAUTO': 'Nifty Auto',
    'NBANK': 'Nifty Bank',
    'NCHEM': 'Nifty Chemicals',
    'NFINSERV': 'Nifty Fin Service',
    'NFINS2550': 'NIFTY FINSRV25 50',
    'NFINSXB': 'Nifty FinSerExBnk',
    'NFMCG': 'Nifty FMCG',
    'NHEALTH': 'NIFTY HEALTHCARE',
    'NTECH': 'Nifty IT',
    'NMEDIA': 'Nifty Media',
    'NMETAL': 'Nifty Metal',
    'NPHARMA': 'Nifty Pharma',
    'NPVTBANK': 'Nifty Pvt Bank',
    'NPSUBANK': 'Nifty PSU Bank',
    'NREALTY': 'Nifty Realty',
    'NCONDUR': 'NIFTY CONSR DURBL',
    'NOILGAS': 'NIFTY OIL AND GAS',
    'NMSFINS': 'Nifty MS Fin Serv',
    'NMSHC': 'Nifty MS Healthcare',
    'NMSITT': 'Nifty MS IT Telcm',
    'NCAPMRKT': 'Nifty Capital Markets',
    'NCOMM': 'Nifty Commodities',
    'NSERVSEC': 'Nifty Serv Sector',
    'NTRANS': 'Nifty Trans Logis',
    
    # Strategy Indices  
    'N100EWT': 'NIFTY100 EQL WGT',
    'N100LV30': 'NIFTY100 LOWVOL30',
    'N200M30': 'Nifty200Momentm30',
    'N200AL30': 'Nifty200 Alpha 30',
    'N100AL30': 'Nifty100 Alpha 30',
    'NAL50': 'NIFTY ALPHA 50',
    'NALV30': 'NIFTY ALPHALOWVOL',
    'NAQLV30': 'Nifty AQLV 30',
    'NAQVLV30': 'Nifty AQL 30',
    'NDIVOP50': 'Nifty Div Opps 50',
    'NLV50': 'Nifty Low Vol 50',
    'NHBET50': 'Nifty HighBeta 50',
    'NGROW15': 'Nifty GrowSect 15',
    'N100QL30': 'NIFTY100 QUALTY30',
    'N200QL30': 'NIFTY200 QUALITY 30',
    'NQLLV30': 'Nifty Qlty LV 30',
    'N500QL50': 'Nifty500 Qlty50',
    'N500M50': 'Nifty500Momentm50',
    'N500LV50': 'Nifty500 LowVol50',
    'N500V50': 'Nifty500 Value 50',
    'N500MQLV': 'Nifty500 MQVLv50',
    'N500MQ50': 'Nifty Multi MQ 50',
    'N50V20': 'Nifty50 Value 20',
    'N200V30': 'Nifty200 Value 30',
    'NMC150M50': 'NIFTYM150MOMNTM50',
    'NMC150Q': 'NIFTY M150 QLTY50',
    'N500FQ30': 'NIFTY500 FLEXICAP',
    'NSC250Q': 'Nifty Sml250 Q50',
    'NMSCMQ': 'NiftyMS400 MQ 100',
    'NSC250MQ': 'NiftySml250MQ 100',
    'N50SH': 'Nifty50 Shariah',
    'N500SH': 'Nifty500 Shariah',
    'NSH25': 'Nifty Shariah 25',
    
    # Thematic Indices
    'NICON': 'Nifty Consumption',
    'NIDEF': 'Nifty India Defence',
    'NIDIGI': 'NIFTY IND DIGITAL',
    'NIIL': 'Nifty India Innovation Labs',
    'NIMFG': 'NIFTY INDIA MFG',
    'NCPSE': 'Nifty CPSE',
    'NENRGY': 'Nifty Energy',
    'NEVNAA': 'Nifty EV & New Age Auto',
    'NHOUS': 'Nifty Housing',
    'N100ESG': 'NIFTY100 ESG',
    'N100ESGE': 'Nifty100 Enh ESG',
    'N100ESGSL': 'Nifty100ESGSecLdr',
    'NINFRA': 'Nifty Infra',
    'NTOUR': 'Nifty Ind Tourism',
    'NINACON': 'Nifty New Consump',
    'NCHOUS': 'Nifty CoreHousing',
    'NMSICON': 'Nifty MS Ind Cons',
    'NMOBIL': 'Nifty Mobility',
    'NNCCON': 'Nifty NonCyc Cons',
    'NRURAL': 'Nifty Rural',
    'NIINT': 'Nifty India International',
    'NPSE': 'Nifty PSE',
    'NMNC': 'Nifty MNC',
    'NREIT': 'Nifty REITs & InvITs',
    'NIPO': 'Nifty India IPO',
    'NSMEE': 'Nifty SME Emerge',
    'NIRLPSU': 'Nifty India Listed PSU',
    'NBIRLA': 'Nifty India Corporate Group Index - Aditya Birla Group',
    'NMAHIN': 'Nifty India Corporate Group Index - Mahindra Group',
    'NTATA': 'Nifty India Corporate Group Index - Tata Group',
    'NTATA25': 'NIFTY TATA 25 CAP',
    'NMAATR': 'Nifty Corp MAATR',
    'NMF5032': 'NIFTY MULTI MFG',
    'NINF5032': 'NIFTY MULTI INFRA',
    'NWAVES': 'Nifty Waves',
    
    # Mutual Fund & Bond Indices
    'DSPQ': 'DSP Quant',
    'DSP ELSS': 'DSP ELSS',
    'KBIK CON': 'KBIK Construction',
    'KBIK GOLD': 'KBIK Gold',
    'AXISINVE': 'Axis Investment',
    'UTI FLEX': 'UTI Flexi Cap',
    'ICICI SIL': 'ICICI Silverline',
    'N10YRGS': 'Nifty GS 10Yr Cln',
    'NIFTY 10 YR BENCHMARK G-SEC.1': 'Nifty 10 YR Benchmark G-SEC',
}

# Create reverse mapping (full name to short code)
FULLNAME_TO_COLUMN = {v: k for k, v in COLUMN_TO_FULLNAME.items()}
